In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [4]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [5]:
np.vstack((x,y))

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [6]:
z = x + y
z

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [7]:
print('type = ',x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  1
shape =  (5,)
size =  5


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [8]:
w = np.array([[11, 12],[13, 14],[15,16]])
w
# h = w.transpose()

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [9]:
z = np.array([[1],[2],[3]])
z


array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [10]:
newArray = np.hstack((z, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [11]:
for item in newArray.flat:
    print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [12]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [13]:
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [15]:
print("the smallest value is: ",newArray.min())
print("the biggest value is: ",newArray.max())

the smallest value is:  0
the biggest value is:  15


## Q#12: Print the first row of "newArray" using indexing.

In [16]:
newArray[0][0] , newArray[0][1] , newArray[0][2]

(0, 10, 11)

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [17]:
newArray[1,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [18]:
newArray[0][0]


0

In [19]:
newArray[1][2]

13

## Q#15: Change the shape of "newArray" to (9,1).

In [21]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [22]:
newArray.reshape(3,2) # we can,t reshape the array because the size is 9x1

ValueError: ignored

# Well Done 🎉

In [ ]:
newArray.transpose()